export {default as LandingPage} from './landingPage'
export {default as SellerRegistration} from './sellerRegistration'
export {default as ConsumerRegistration} from './consumerRegistration'
export {default as DeliveryAgentRegistration} from './deliveryAgentRegistration'
export {default as ProductsCreation} from './productsCreation'
export {default as ProductsTable} from './productsTable'